apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yzts
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0032-tenant/cin4s-839-0032-app/devfile-sample-yzts@sha256:743a54aef28a6e453f11ceec4302bb6e6a2470ebfbee664d9e721877fc20aeaa
        name: my-nodejs
        resources: {}
status: {}
